### ISSUE TITLE
How to deal with the caching gotcha

### ISSUE THREAD

**Issue by fvsch** [fabianmichael/kirby-typography#5]
Hi,

So I spent a few hours the other day trying to get settings for a multilingual site working. Most of the settings I was declaring, in `site/config/config.php` or in `languages/fr.php` were not working. for instance I couldn't get the `&nbsp;` added before double punctuation marks. It just wouldn't work.

Today I realized that this plugin uses a week-long cache, and what I was seeing was perhaps the result from older settings. So I set `c::set('typography.debug', true);` and taddaaaa it worked.

I'm suspecting many users would have this issue, if following this scenario:
1. Install plugin
2. Enable it
3. Load a page to see the result
4. Tweak configuration
5. Refresh page: nothing changes

Different ways to prevent that:
1. Document it more prominently in the README (might still be easy to miss)
2. Default `typography.debug` to the value of the `debug` config.
3. Best but more complex: build a hash string out of the typography config values, and use it as a key when storing the cache. Changed config = cache doesn't match anymore.

**Comment by fabianmichael** [comment]
Hi,
sorry you had to so much time with this issue.

I’ve installed the langkit and tried to reproduce your issue, but without success. Let me explaing, how caching actually works:
- The plugin’s cache internally uses Kirby’s File cache driver from the Toolkit and adds a few methods.
- When the `parse()` method of the Typography component is called, it first checks, if it is a _multilang_ installation. If so, the plugin looks for language-specific options, defined via `l::set()` for the current language and overrides existing settings in `$kirby->options[]` array. If not, the settings from the config file are used.
- If debug mode is turned off, it then creates a cache key, conposed of the _current plugin version_, _the serialized string of current settings_ and the given string, which should be parsed. This composition is then hashed using `md5()`. This hash is the cache key, which does not expire. If either a setting, the plugin version or the text itself changes, the cache key should also change.

---

So in theory, it should just work as you suggested. Turning off cache is not really an option, because PHP-Typography is a greedy monster, when it comes to CPU time. On my local machine (a 2,5 GHz Quad-Core MacBook Pro 15˝), PHP execution time often is about 500 ms, when in debug mode. I think most webspace providers offer much less resources for processing, which can often result in inacceptable loading times. 

---

Did you use `l::set()` in the language files instead of `c::set()? If you hav eany idea, what could have caused your problem, I would be glad if I could help you. But I have currently no idea, why your content did not update correctly.

Nevertheless, I added another notice to the README, that language-specific configuration has to happen inside the language files instead of the config file.

**Comment by fvsch** [comment]
Okay I think I identified what made me think it was a cache issue. Not related to the cache in any way. I was having one particular problem and I thought it went away after disabling the cache, but actually it did _not_ (I was testing the wrong thing).

I'll let you close this bug so that you can tag as invalid (rather than bug), maybe?

And thanks for the detailed explanation of how the caching works. :)

**Comment by fabianmichael** [comment]
You’re welcome. :-)

**Comment by fvsch** [comment]
For the record my misunderstanding came from a mix of trying to use `$field->smartypants()` which doesnt exist (https://github.com/getkirby/kirby/issues/455) and this issue: https://github.com/fabianmichael/kirby-typography/issues/8.
